/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horario.gui;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author byZeRo
 */
public class AltaUsuario extends javax.swing.JDialog {

    HorarioLayout father = new HorarioLayout();

    /**
     * Creates new form AltaUsuario
     */
    public AltaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        father = (HorarioLayout) parent;
        initComponents();

        try {
            File imagen = new File("src\\horario\\img\\reloj.png");
            Image image = ImageIO.read(imagen);
            this.setIconImage(image);
            this.setTitle("ALTA HORARIO");
        } catch (IOException ex) {
            Logger.getLogger(AltaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGDias = new javax.swing.ButtonGroup();
        jPHoras = new javax.swing.JPanel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPDias = new javax.swing.JPanel();
        jRBLunes = new javax.swing.JRadioButton();
        jRBMartes = new javax.swing.JRadioButton();
        jRBMiercoles = new javax.swing.JRadioButton();
        jRBJueves = new javax.swing.JRadioButton();
        jRBViernes = new javax.swing.JRadioButton();
        jTModulo = new javax.swing.JTextField();
        jLNombreModulo = new javax.swing.JLabel();
        jLError = new javax.swing.JLabel();
        jBAniadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPHoras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selcciona las horas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jCheckBox6.setText("13:30 14:25");

        jCheckBox5.setText("12:35 13:30");

        jCheckBox4.setText("11:40 12:35");

        jCheckBox3.setText("10:15 11:10");

        jCheckBox2.setText("9:20 10:15");

        jCheckBox1.setText("8:25 9:20");

        javax.swing.GroupLayout jPHorasLayout = new javax.swing.GroupLayout(jPHoras);
        jPHoras.setLayout(jPHorasLayout);
        jPHorasLayout.setHorizontalGroup(
            jPHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHorasLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox4))
                .addGap(95, 95, 95)
                .addGroup(jPHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox5))
                .addGap(97, 97, 97)
                .addGroup(jPHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPHorasLayout.setVerticalGroup(
            jPHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6))
                .addContainerGap())
        );

        jPDias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecciona un día", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        bGDias.add(jRBLunes);
        jRBLunes.setText("Lunes");

        bGDias.add(jRBMartes);
        jRBMartes.setText("Martes");

        bGDias.add(jRBMiercoles);
        jRBMiercoles.setText("Miercoles");

        bGDias.add(jRBJueves);
        jRBJueves.setText("Jueves");

        bGDias.add(jRBViernes);
        jRBViernes.setText("Viernes");

        javax.swing.GroupLayout jPDiasLayout = new javax.swing.GroupLayout(jPDias);
        jPDias.setLayout(jPDiasLayout);
        jPDiasLayout.setHorizontalGroup(
            jPDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDiasLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jRBLunes)
                .addGap(18, 18, 18)
                .addComponent(jRBMartes)
                .addGap(18, 18, 18)
                .addComponent(jRBMiercoles)
                .addGap(18, 18, 18)
                .addComponent(jRBJueves)
                .addGap(18, 18, 18)
                .addComponent(jRBViernes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPDiasLayout.setVerticalGroup(
            jPDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDiasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBLunes)
                    .addComponent(jRBMartes)
                    .addComponent(jRBMiercoles)
                    .addComponent(jRBJueves)
                    .addComponent(jRBViernes))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLNombreModulo.setText("Introduzca nombre del módulo");

        jLError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLError.setForeground(new java.awt.Color(255, 0, 51));
        jLError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jBAniadir.setText("AÑADIR");
        jBAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAniadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPHoras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPDias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLError, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jBAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLError, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jBAniadir)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAniadirActionPerformed
        if (jTModulo.getText().isEmpty()) {
            jLError.setText("Introduzca un módulo");
        } else if (bGDias.getSelection() == null) {
            jLError.setText("Marque un día");
        } else if (!jCheckBox1.isSelected() && !jCheckBox2.isSelected() && !jCheckBox3.isSelected() && !jCheckBox4.isSelected() && !jCheckBox5.isSelected() && !jCheckBox6.isSelected()) {
            jLError.setText("Marque al menos una hora");
        }
    }//GEN-LAST:event_jBAniadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaUsuario dialog = new AltaUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGDias;
    private javax.swing.JButton jBAniadir;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLError;
    private javax.swing.JLabel jLNombreModulo;
    private javax.swing.JPanel jPDias;
    private javax.swing.JPanel jPHoras;
    private javax.swing.JRadioButton jRBJueves;
    private javax.swing.JRadioButton jRBLunes;
    private javax.swing.JRadioButton jRBMartes;
    private javax.swing.JRadioButton jRBMiercoles;
    private javax.swing.JRadioButton jRBViernes;
    private javax.swing.JTextField jTModulo;
    // End of variables declaration//GEN-END:variables
}
