/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horario.gui;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author byZeRo
 */
public class HorarioLayout extends javax.swing.JFrame {

    /**
     * Creates new form HorarioLayout
     */
    public HorarioLayout() {
        initComponents();
        
         try {
            File imagen = new File("src\\horario\\img\\reloj.png");
            Image image = ImageIO.read(imagen);
            this.setIconImage(image);
            this.setTitle("HORARIO");
        } catch (IOException ex) {
            Logger.getLogger(AltaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCabeceraPrincipal = new javax.swing.JPanel();
        jLCabeceraPrincipal = new javax.swing.JLabel();
        jPCuerpoPrincipal = new javax.swing.JPanel();
        jPLunes = new javax.swing.JPanel();
        jLLunes = new javax.swing.JLabel();
        jPLunesCuerpo = new javax.swing.JPanel();
        jB11 = new javax.swing.JButton();
        jB12 = new javax.swing.JButton();
        jB13 = new javax.swing.JButton();
        jB14 = new javax.swing.JButton();
        jB15 = new javax.swing.JButton();
        jB16 = new javax.swing.JButton();
        jB17 = new javax.swing.JButton();
        jPMartes = new javax.swing.JPanel();
        jLMartes = new javax.swing.JLabel();
        jPMartesCuerpo = new javax.swing.JPanel();
        jB21 = new javax.swing.JButton();
        jB22 = new javax.swing.JButton();
        jB23 = new javax.swing.JButton();
        JB24 = new javax.swing.JButton();
        jB25 = new javax.swing.JButton();
        jB26 = new javax.swing.JButton();
        jB27 = new javax.swing.JButton();
        jPMiercoles = new javax.swing.JPanel();
        jPMiercolesCuerpo = new javax.swing.JPanel();
        jB31 = new javax.swing.JButton();
        jB32 = new javax.swing.JButton();
        jB33 = new javax.swing.JButton();
        jB34 = new javax.swing.JButton();
        jB35 = new javax.swing.JButton();
        jB36 = new javax.swing.JButton();
        jB37 = new javax.swing.JButton();
        jLMiercoles = new javax.swing.JLabel();
        jPJueves = new javax.swing.JPanel();
        jLJueves = new javax.swing.JLabel();
        jPJuevesCuerpo = new javax.swing.JPanel();
        jB41 = new javax.swing.JButton();
        jB42 = new javax.swing.JButton();
        jB43 = new javax.swing.JButton();
        jB44 = new javax.swing.JButton();
        jB45 = new javax.swing.JButton();
        jB46 = new javax.swing.JButton();
        jB47 = new javax.swing.JButton();
        jPViernes = new javax.swing.JPanel();
        jLViernes = new javax.swing.JLabel();
        jPViernesCuerpo = new javax.swing.JPanel();
        jB51 = new javax.swing.JButton();
        jB52 = new javax.swing.JButton();
        jB53 = new javax.swing.JButton();
        jB54 = new javax.swing.JButton();
        jB55 = new javax.swing.JButton();
        jB56 = new javax.swing.JButton();
        jB57 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlta = new javax.swing.JMenu();
        jMBaja = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1130, 600));

        jPCabeceraPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        jLCabeceraPrincipal.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLCabeceraPrincipal.setForeground(new java.awt.Color(51, 102, 255));
        jLCabeceraPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCabeceraPrincipal.setText("HORARIO");

        javax.swing.GroupLayout jPCabeceraPrincipalLayout = new javax.swing.GroupLayout(jPCabeceraPrincipal);
        jPCabeceraPrincipal.setLayout(jPCabeceraPrincipalLayout);
        jPCabeceraPrincipalLayout.setHorizontalGroup(
            jPCabeceraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCabeceraPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCabeceraPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPCabeceraPrincipalLayout.setVerticalGroup(
            jPCabeceraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCabeceraPrincipalLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLCabeceraPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPCabeceraPrincipal, java.awt.BorderLayout.PAGE_START);

        jPCuerpoPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        jPCuerpoPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jPCuerpoPrincipal.setLayout(new java.awt.GridLayout(1, 0));

        jPLunes.setBackground(new java.awt.Color(0, 0, 0));
        jPLunes.setLayout(new java.awt.BorderLayout());

        jLLunes.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLLunes.setForeground(new java.awt.Color(51, 204, 255));
        jLLunes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLunes.setText("LUNES");
        jPLunes.add(jLLunes, java.awt.BorderLayout.PAGE_START);

        jPLunesCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        jPLunesCuerpo.setForeground(new java.awt.Color(0, 0, 0));
        jPLunesCuerpo.setLayout(new java.awt.GridLayout(7, 1));

        jB11.setBackground(new java.awt.Color(102, 102, 102));
        jB11.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB11.setForeground(new java.awt.Color(51, 204, 255));
        jB11.setText("PMDM");
        jPLunesCuerpo.add(jB11);

        jB12.setBackground(new java.awt.Color(102, 102, 102));
        jB12.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB12.setForeground(new java.awt.Color(51, 204, 255));
        jB12.setText("PMDM");
        jPLunesCuerpo.add(jB12);

        jB13.setBackground(new java.awt.Color(102, 102, 102));
        jB13.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB13.setForeground(new java.awt.Color(51, 204, 255));
        jB13.setText("PMDM");
        jPLunesCuerpo.add(jB13);

        jB14.setBackground(new java.awt.Color(102, 102, 102));
        jB14.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB14.setForeground(new java.awt.Color(51, 204, 255));
        jB14.setText("RECREO");
        jPLunesCuerpo.add(jB14);

        jB15.setBackground(new java.awt.Color(102, 102, 102));
        jB15.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB15.setForeground(new java.awt.Color(51, 204, 255));
        jB15.setText("AD");
        jPLunesCuerpo.add(jB15);

        jB16.setBackground(new java.awt.Color(102, 102, 102));
        jB16.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB16.setForeground(new java.awt.Color(51, 204, 255));
        jB16.setText("AD");
        jPLunesCuerpo.add(jB16);

        jB17.setBackground(new java.awt.Color(102, 102, 102));
        jB17.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB17.setForeground(new java.awt.Color(51, 204, 255));
        jB17.setText("AD");
        jPLunesCuerpo.add(jB17);

        jPLunes.add(jPLunesCuerpo, java.awt.BorderLayout.CENTER);

        jPCuerpoPrincipal.add(jPLunes);

        jPMartes.setBackground(new java.awt.Color(0, 0, 0));
        jPMartes.setLayout(new java.awt.BorderLayout());

        jLMartes.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLMartes.setForeground(new java.awt.Color(0, 153, 255));
        jLMartes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMartes.setText("MARTES");
        jPMartes.add(jLMartes, java.awt.BorderLayout.PAGE_START);

        jPMartesCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        jPMartesCuerpo.setLayout(new java.awt.GridLayout(7, 1));

        jB21.setBackground(new java.awt.Color(102, 102, 102));
        jB21.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB21.setForeground(new java.awt.Color(0, 153, 255));
        jB21.setText("SGE");
        jPMartesCuerpo.add(jB21);

        jB22.setBackground(new java.awt.Color(102, 102, 102));
        jB22.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB22.setForeground(new java.awt.Color(0, 153, 255));
        jB22.setText("SGE");
        jPMartesCuerpo.add(jB22);

        jB23.setBackground(new java.awt.Color(102, 102, 102));
        jB23.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB23.setForeground(new java.awt.Color(0, 153, 255));
        jB23.setText("SGE");
        jPMartesCuerpo.add(jB23);

        JB24.setBackground(new java.awt.Color(102, 102, 102));
        JB24.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        JB24.setForeground(new java.awt.Color(0, 153, 255));
        JB24.setText("RECREO");
        jPMartesCuerpo.add(JB24);

        jB25.setBackground(new java.awt.Color(102, 102, 102));
        jB25.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB25.setForeground(new java.awt.Color(0, 153, 255));
        jB25.setText("EIE");
        jPMartesCuerpo.add(jB25);

        jB26.setBackground(new java.awt.Color(102, 102, 102));
        jB26.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB26.setForeground(new java.awt.Color(0, 153, 255));
        jB26.setText("EIE");
        jPMartesCuerpo.add(jB26);

        jB27.setBackground(new java.awt.Color(102, 102, 102));
        jB27.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB27.setForeground(new java.awt.Color(0, 153, 255));
        jB27.setText("EIE");
        jPMartesCuerpo.add(jB27);

        jPMartes.add(jPMartesCuerpo, java.awt.BorderLayout.CENTER);

        jPCuerpoPrincipal.add(jPMartes);

        jPMiercoles.setBackground(new java.awt.Color(0, 0, 0));
        jPMiercoles.setLayout(new java.awt.BorderLayout());

        jPMiercolesCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        jPMiercolesCuerpo.setLayout(new java.awt.GridLayout(7, 1));

        jB31.setBackground(new java.awt.Color(102, 102, 102));
        jB31.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB31.setForeground(new java.awt.Color(51, 102, 255));
        jB31.setText("SGE");
        jPMiercolesCuerpo.add(jB31);

        jB32.setBackground(new java.awt.Color(102, 102, 102));
        jB32.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB32.setForeground(new java.awt.Color(51, 102, 255));
        jB32.setText("SGE");
        jPMiercolesCuerpo.add(jB32);

        jB33.setBackground(new java.awt.Color(102, 102, 102));
        jB33.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB33.setForeground(new java.awt.Color(51, 102, 255));
        jB33.setText("EIE");
        jPMiercolesCuerpo.add(jB33);

        jB34.setBackground(new java.awt.Color(102, 102, 102));
        jB34.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB34.setForeground(new java.awt.Color(51, 102, 255));
        jB34.setText("RECREO");
        jPMiercolesCuerpo.add(jB34);

        jB35.setBackground(new java.awt.Color(102, 102, 102));
        jB35.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB35.setForeground(new java.awt.Color(51, 102, 255));
        jB35.setText("DI");
        jPMiercolesCuerpo.add(jB35);

        jB36.setBackground(new java.awt.Color(102, 102, 102));
        jB36.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB36.setForeground(new java.awt.Color(51, 102, 255));
        jB36.setText("DI");
        jPMiercolesCuerpo.add(jB36);

        jB37.setBackground(new java.awt.Color(102, 102, 102));
        jB37.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB37.setForeground(new java.awt.Color(51, 102, 255));
        jB37.setText("DI");
        jPMiercolesCuerpo.add(jB37);

        jPMiercoles.add(jPMiercolesCuerpo, java.awt.BorderLayout.CENTER);

        jLMiercoles.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLMiercoles.setForeground(new java.awt.Color(51, 102, 255));
        jLMiercoles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMiercoles.setText("MIERCOLES");
        jPMiercoles.add(jLMiercoles, java.awt.BorderLayout.PAGE_START);

        jPCuerpoPrincipal.add(jPMiercoles);

        jPJueves.setBackground(new java.awt.Color(0, 0, 0));
        jPJueves.setLayout(new java.awt.BorderLayout());

        jLJueves.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLJueves.setForeground(new java.awt.Color(0, 153, 255));
        jLJueves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLJueves.setText("JUEVES");
        jPJueves.add(jLJueves, java.awt.BorderLayout.PAGE_START);

        jPJuevesCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        jPJuevesCuerpo.setLayout(new java.awt.GridLayout(7, 1));

        jB41.setBackground(new java.awt.Color(102, 102, 102));
        jB41.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB41.setForeground(new java.awt.Color(51, 153, 255));
        jB41.setText("PSP");
        jPJuevesCuerpo.add(jB41);

        jB42.setBackground(new java.awt.Color(102, 102, 102));
        jB42.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB42.setForeground(new java.awt.Color(51, 153, 255));
        jB42.setText("PSP");
        jPJuevesCuerpo.add(jB42);

        jB43.setBackground(new java.awt.Color(102, 102, 102));
        jB43.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB43.setForeground(new java.awt.Color(51, 153, 255));
        jB43.setText("PSP");
        jPJuevesCuerpo.add(jB43);

        jB44.setBackground(new java.awt.Color(102, 102, 102));
        jB44.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB44.setForeground(new java.awt.Color(51, 153, 255));
        jB44.setText("RECREO");
        jPJuevesCuerpo.add(jB44);

        jB45.setBackground(new java.awt.Color(102, 102, 102));
        jB45.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB45.setForeground(new java.awt.Color(51, 153, 255));
        jB45.setText("AD");
        jPJuevesCuerpo.add(jB45);

        jB46.setBackground(new java.awt.Color(102, 102, 102));
        jB46.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB46.setForeground(new java.awt.Color(51, 153, 255));
        jB46.setText("AD");
        jPJuevesCuerpo.add(jB46);

        jB47.setBackground(new java.awt.Color(102, 102, 102));
        jB47.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB47.setForeground(new java.awt.Color(51, 153, 255));
        jB47.setText("AD");
        jPJuevesCuerpo.add(jB47);

        jPJueves.add(jPJuevesCuerpo, java.awt.BorderLayout.CENTER);

        jPCuerpoPrincipal.add(jPJueves);

        jPViernes.setBackground(new java.awt.Color(0, 0, 0));
        jPViernes.setLayout(new java.awt.BorderLayout());

        jLViernes.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLViernes.setForeground(new java.awt.Color(51, 204, 255));
        jLViernes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLViernes.setText("VIERNES");
        jPViernes.add(jLViernes, java.awt.BorderLayout.PAGE_START);

        jPViernesCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        jPViernesCuerpo.setLayout(new java.awt.GridLayout(7, 1));

        jB51.setBackground(new java.awt.Color(102, 102, 102));
        jB51.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB51.setForeground(new java.awt.Color(0, 204, 255));
        jB51.setText("DI");
        jPViernesCuerpo.add(jB51);

        jB52.setBackground(new java.awt.Color(102, 102, 102));
        jB52.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB52.setForeground(new java.awt.Color(0, 204, 255));
        jB52.setText("DI");
        jPViernesCuerpo.add(jB52);

        jB53.setBackground(new java.awt.Color(102, 102, 102));
        jB53.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB53.setForeground(new java.awt.Color(0, 204, 255));
        jB53.setText("DI");
        jPViernesCuerpo.add(jB53);

        jB54.setBackground(new java.awt.Color(102, 102, 102));
        jB54.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB54.setForeground(new java.awt.Color(0, 204, 255));
        jB54.setText("RECREO");
        jPViernesCuerpo.add(jB54);

        jB55.setBackground(new java.awt.Color(102, 102, 102));
        jB55.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB55.setForeground(new java.awt.Color(0, 204, 255));
        jB55.setText("PMDM");
        jPViernesCuerpo.add(jB55);

        jB56.setBackground(new java.awt.Color(102, 102, 102));
        jB56.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB56.setForeground(new java.awt.Color(0, 204, 255));
        jB56.setText("PMDM");
        jPViernesCuerpo.add(jB56);

        jB57.setBackground(new java.awt.Color(102, 102, 102));
        jB57.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jB57.setForeground(new java.awt.Color(0, 204, 255));
        jB57.setText("PROYECTO");
        jPViernesCuerpo.add(jB57);

        jPViernes.add(jPViernesCuerpo, java.awt.BorderLayout.CENTER);

        jPCuerpoPrincipal.add(jPViernes);

        getContentPane().add(jPCuerpoPrincipal, java.awt.BorderLayout.CENTER);

        jMAlta.setText("Alta");
        jMAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMAltaMousePressed(evt);
            }
        });
        jMenuBar1.add(jMAlta);

        jMBaja.setText("Lista");
        jMenuBar1.add(jMBaja);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMAltaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMAltaMousePressed
        AltaUsuario altaUsuario=new AltaUsuario(this, true);
        altaUsuario.setVisible(true);
    }//GEN-LAST:event_jMAltaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HorarioLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HorarioLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HorarioLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HorarioLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HorarioLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB24;
    private javax.swing.JButton jB11;
    private javax.swing.JButton jB12;
    private javax.swing.JButton jB13;
    private javax.swing.JButton jB14;
    private javax.swing.JButton jB15;
    private javax.swing.JButton jB16;
    private javax.swing.JButton jB17;
    private javax.swing.JButton jB21;
    private javax.swing.JButton jB22;
    private javax.swing.JButton jB23;
    private javax.swing.JButton jB25;
    private javax.swing.JButton jB26;
    private javax.swing.JButton jB27;
    private javax.swing.JButton jB31;
    private javax.swing.JButton jB32;
    private javax.swing.JButton jB33;
    private javax.swing.JButton jB34;
    private javax.swing.JButton jB35;
    private javax.swing.JButton jB36;
    private javax.swing.JButton jB37;
    private javax.swing.JButton jB41;
    private javax.swing.JButton jB42;
    private javax.swing.JButton jB43;
    private javax.swing.JButton jB44;
    private javax.swing.JButton jB45;
    private javax.swing.JButton jB46;
    private javax.swing.JButton jB47;
    private javax.swing.JButton jB51;
    private javax.swing.JButton jB52;
    private javax.swing.JButton jB53;
    private javax.swing.JButton jB54;
    private javax.swing.JButton jB55;
    private javax.swing.JButton jB56;
    private javax.swing.JButton jB57;
    private javax.swing.JLabel jLCabeceraPrincipal;
    private javax.swing.JLabel jLJueves;
    private javax.swing.JLabel jLLunes;
    private javax.swing.JLabel jLMartes;
    private javax.swing.JLabel jLMiercoles;
    private javax.swing.JLabel jLViernes;
    private javax.swing.JMenu jMAlta;
    private javax.swing.JMenu jMBaja;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPCabeceraPrincipal;
    private javax.swing.JPanel jPCuerpoPrincipal;
    private javax.swing.JPanel jPJueves;
    private javax.swing.JPanel jPJuevesCuerpo;
    private javax.swing.JPanel jPLunes;
    private javax.swing.JPanel jPLunesCuerpo;
    private javax.swing.JPanel jPMartes;
    private javax.swing.JPanel jPMartesCuerpo;
    private javax.swing.JPanel jPMiercoles;
    private javax.swing.JPanel jPMiercolesCuerpo;
    private javax.swing.JPanel jPViernes;
    private javax.swing.JPanel jPViernesCuerpo;
    // End of variables declaration//GEN-END:variables
}
